"""
fid_score.py

Computes the Fréchet Inception Distance (FID) between the real NIH chest X-ray
images and the synthetic images generated by generate_images.py for each rare
finding class.

FID is computed using the torch-fidelity library, which uses an Inception-v3
feature extractor. Lower FID indicates synthetic images are more similar in
distribution to real images.

Results are written to results/fid_results.json.

Usage:
    python src/fid_score.py [--finding Pneumothorax] [--finding Emphysema]
"""

import argparse
import json
import shutil
import tempfile
from pathlib import Path

import torch_fidelity
from PIL import Image
from tqdm import tqdm

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
RESULTS_DIR = ROOT / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

REAL_IMAGE_DIR = DATA_DIR / "rare_findings"
SYNTH_IMAGE_DIR = DATA_DIR / "synthetic_images"

ALL_FINDINGS = ["Pneumothorax", "Emphysema"]


def collect_png_paths(directory: Path) -> list[Path]:
    """Return all PNG/JPG image paths under a directory (non-recursive)."""
    exts = {".png", ".jpg", ".jpeg"}
    return [p for p in directory.iterdir() if p.suffix.lower() in exts]


def prepare_temp_dir(image_paths: list[Path], max_images: int = 2048) -> Path:
    """
    Copy images into a temporary directory as RGB PNGs so torch-fidelity can
    read them uniformly regardless of the original format or color mode.

    torch-fidelity requires a directory of images; it cannot accept file lists.

    Returns the Path of the temporary directory (caller must clean it up).
    """
    tmp = Path(tempfile.mkdtemp())
    for i, src in enumerate(tqdm(image_paths[:max_images], desc="  Staging images", leave=False)):
        dst = tmp / f"{i:06d}.png"
        img = Image.open(src).convert("RGB")
        img.save(dst, format="PNG")
    return tmp


def compute_fid(finding: str, max_images: int = 2048) -> dict:
    """
    Compute FID for a single finding class.

    Args:
        finding:    Name of the rare finding class.
        max_images: Maximum number of images to use per set (real and synthetic).
                    torch-fidelity recommends ≥2048 for reliable FID estimates;
                    use fewer only when the dataset is smaller.

    Returns:
        dict with keys: finding, n_real, n_synth, fid.
    """
    real_dir = REAL_IMAGE_DIR / finding
    synth_dir = SYNTH_IMAGE_DIR / finding

    if not real_dir.exists():
        print(f"  [SKIP] Real image directory not found: {real_dir}")
        return {"finding": finding, "n_real": 0, "n_synth": 0, "fid": None, "error": "no real images"}

    if not synth_dir.exists():
        print(f"  [SKIP] Synthetic image directory not found: {synth_dir}")
        return {"finding": finding, "n_real": 0, "n_synth": 0, "fid": None, "error": "no synth images"}

    real_paths = collect_png_paths(real_dir)
    synth_paths = [p for p in collect_png_paths(synth_dir) if p.name != "failed.json"]

    if not real_paths or not synth_paths:
        return {
            "finding": finding,
            "n_real": len(real_paths),
            "n_synth": len(synth_paths),
            "fid": None,
            "error": "insufficient images",
        }

    print(f"\n  Finding: {finding}")
    print(f"  Real images:  {len(real_paths)} (using up to {max_images})")
    print(f"  Synth images: {len(synth_paths)} (using up to {max_images})")

    # torch-fidelity needs directories, not path lists, so we stage into temp dirs
    tmp_real = prepare_temp_dir(real_paths, max_images)
    tmp_synth = prepare_temp_dir(synth_paths, max_images)

    try:
        metrics = torch_fidelity.calculate_metrics(
            input1=str(tmp_real),
            input2=str(tmp_synth),
            cuda=False,          # set to True if GPU is available
            fid=True,
            isc=False,           # skip IS — requires more synthetic samples
            kid=False,
            verbose=False,
        )
        fid_value = round(metrics["frechet_inception_distance"], 4)
        print(f"  FID = {fid_value}")
    finally:
        # Always clean up temp dirs even if computation fails
        shutil.rmtree(tmp_real, ignore_errors=True)
        shutil.rmtree(tmp_synth, ignore_errors=True)

    return {
        "finding": finding,
        "n_real": min(len(real_paths), max_images),
        "n_synth": min(len(synth_paths), max_images),
        "fid": fid_value,
    }


def main(findings: list[str], max_images: int = 2048) -> None:
    """
    Compute FID for each specified finding class and write results to JSON.

    Args:
        findings:   List of finding class names to evaluate.
        max_images: Images per set passed to the FID computation.
    """
    print("Computing FID scores …")
    results = []
    for finding in findings:
        result = compute_fid(finding, max_images)
        results.append(result)

    output_path = RESULTS_DIR / "fid_results.json"
    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nFID results saved → {output_path}")

    # Summary table
    print(f"\n{'Finding':<16} {'n_real':>8} {'n_synth':>9} {'FID':>10}")
    print("─" * 46)
    for r in results:
        fid_str = f"{r['fid']:.2f}" if r["fid"] is not None else "N/A"
        print(f"{r['finding']:<16} {r['n_real']:>8} {r['n_synth']:>9} {fid_str:>10}")

    print(
        "\nInterpretation: FID < 50 is roughly 'decent quality'; "
        "lower is better. Medical images typically yield higher FID "
        "against general-purpose generative models."
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compute FID between real and synthetic X-rays.")
    parser.add_argument(
        "--finding",
        action="append",
        dest="findings",
        choices=ALL_FINDINGS,
        help="Finding class to evaluate (repeat for multiple). Defaults to all three.",
    )
    parser.add_argument(
        "--max-images",
        type=int,
        default=2048,
        help="Max images per set used for FID (default: 2048). Reduce if memory-constrained.",
    )
    args = parser.parse_args()
    findings = args.findings if args.findings else ALL_FINDINGS
    main(findings=findings, max_images=args.max_images)
